# Generated by Django 4.2.7 on 2024-02-13 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment_product",
            fields=[
                ("invest_id", models.AutoField(primary_key=True, serialize=False)),
                ("investment_name", models.CharField(max_length=50, unique=True)),
                ("date_upload", models.DateTimeField(auto_now_add=True, unique=True)),
                ("total_unit", models.IntegerField()),
                ("minimum_unit", models.IntegerField()),
                ("maximum_unit", models.IntegerField()),
                ("price_per_unit", models.IntegerField()),
                ("description", models.CharField(max_length=500)),
                (
                    "product_picture",
                    models.ImageField(null=True, upload_to="productImage/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Agriculture", "Agriculture"),
                            ("Electronicą", "Electronics"),
                            ("Real Estate", "Real Estate"),
                            ("Forex", "Forex"),
                            ("Cryptocurrency", "Cryptocurrency"),
                            ("Solar energy", "Solar energy"),
                        ],
                        default=None,
                        max_length=20,
                    ),
                ),
                (
                    "approved",
                    models.CharField(default="unapproved", max_length=10, null=True),
                ),
                ("category_display", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
