# Generated by Django 4.2.7 on 2024-01-29 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="profile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(max_length=150, null=True)),
                ("phone", models.CharField(max_length=11, null=True, unique=True)),
                ("date_of_birth", models.DateField(max_length=11, null=True)),
                ("gender", models.CharField(max_length=6, null=True)),
                (
                    "nationality",
                    models.CharField(
                        choices=[
                            ("Nigeria", "Nigeria"),
                            ("Ghana", "Ghana"),
                            ("United Kingdom", "UK"),
                            ("USA", "USA"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Abia", "Abia"),
                            ("Oyo", "Oyo"),
                            ("Osun", "Osun"),
                            ("Lagos", "Lagos"),
                            ("Kano", "Kano"),
                            ("Abuja", "Abuja"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "identity_card_name",
                    models.CharField(
                        choices=[
                            ("International Passport", "International Passport"),
                            ("Driver's license", "Driver's license"),
                            ("Voter's card", "Voter's card"),
                            ("Resigned", "Resigned"),
                            ("NIMC", "NIMC"),
                        ],
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "identity_card_number",
                    models.CharField(max_length=150, null=True, unique=True),
                ),
                (
                    "means_of_identity",
                    models.ImageField(null=True, upload_to="identityImage/"),
                ),
                (
                    "profile_picture",
                    models.ImageField(null=True, upload_to="profileImage/"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("MD", "MD"),
                            ("CEO", "CEO"),
                            ("HOD", "HOD"),
                            ("Accountant", "Accountant"),
                            ("Secretary", "Secretary"),
                            ("Admin", "Admin"),
                            ("Store Manager", "Store Manager"),
                            ("Delivery Agent", "Delivery Agent"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Customer care", "Customer care"),
                            ("Sales", "Sales"),
                            ("Account", "Account"),
                            ("HR", "HR"),
                            ("Marketing", "Marketing"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("Married", "Married"),
                            ("Divorce", "Divorce"),
                            ("Complicated", "Complicated"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("staff", models.BooleanField(default=False)),
                ("next_of_kin", models.CharField(max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Suspended", "Suspended"),
                            ("On leave", "On leave"),
                            ("Resigned", "Resigned"),
                            ("Retired", "Retired"),
                        ],
                        default="Active",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
