# Generated by Django 4.2.7 on 2024-02-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="identity_card_number",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
