"""
Django settings for investmentpjt project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#2d4^o*+my%6)k1w3c7nl6#%=9d3xpzk*(u^q5lobikkym9*3j"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#here i can put any hosting address possible that user can type as ther are searching for my website 
ALLOWED_HOSTS = [
    '127.0.0.1',
    'www.investmentproject.com',
    'investmentproject.co'
    ]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "bootstrapform",
    "investmentpjt.investapp",
    "investmentpjt.userapp",
    "investmentpjt.referralapp",
    "investmentpjt.transactionapp", 
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "investmentpjt.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['%s/templates/' % (PROJECT_DIR),],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "investmentpjt.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# the database command below is for mysql server 
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": 'investmentproject_db',
        "USER": 'root',
        "PASSWORD": 'olasunkanmi60@',
        "HOST": '127.0.0.1',
        "PORT": '3306',
        "OPTIONS": {
            'autocommit': True,
            }
        
    }
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

#to use local server, the email will be sent to the cand prompt👇
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

#to use email generated by server in which it will be sent to the user in their mail 👇

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST ="smtp.gmail.com"
# EMAIL_PORT =587
# EMAIL_HOST_USER ="your email"
# EMAIL_HOST_PASSWORD ="*********"
# EMAIL_USE_TLS = True


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS =[
    os.path.join(BASE_DIR, 'static')
]

MEDIA_URL='media/'
MEDIA_ROOT =os.path.join(BASE_DIR, 'media') 



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL ='home'
LOGOUT_REDIRECT_URL ='login'
